### ISSUE TITLE
text blurry

### ISSUE THREAD

**Issue by Davidyanlong** [SeregPie/THREE.TextTexture#10]
when window.devicePixelRatio >1  , text is blurry ,you need canvas size is :
`
ctx.canvas.width = this.imageWidthInPixels * dpr;

ctx.canvas.height = this.imageHeightInPixels * dpr;

ctx.canvas.style.width = this.imageWidthInPixels   +'px';

ctx.canvas.style.height = this.imageHeightInPixels  +'px';

`
eg:  [https://codepen.io/davidyanlong/pen/VBrxOG)](https://codepen.io/davidyanlong/pen/VBrxOG)

**Comment by SeregPie** [comment]
Hi. Thank you for report. I was about to implement this change then I found out, that it is not needed, if you just set `renderer.setPixelRatio(devicePixelRatio);`. I wrote this one line in the demo and it looks good on zoom.

**Comment by Davidyanlong** [comment]
Hi,I wrote code `renderer.setPixelRatio(devicePixelRatio);` It's really clearer, but when devicePixelRatio>1 ,not wrote  

```
ctx.canvas.width = this.imageWidthInPixels * dpr;

ctx.canvas.height = this.imageHeightInPixels * dpr;

ctx.canvas.style.width = this.imageWidthInPixels +'px';

ctx.canvas.style.height = this.imageHeightInPixels +'px';
```

text is  blurry.
![image](https://user-images.githubusercontent.com/10626549/43708360-d9f3c9f2-999c-11e8-9624-b4741384fd5e.png)
VS
![image](https://user-images.githubusercontent.com/10626549/43708388-eb4543f2-999c-11e8-9340-3c5a82ab171d.png)

**Comment by SeregPie** [comment]
You need to set the right `fontSize`.
Check out [TextSprite](https://seregpie.github.io/THREE.TextSprite/). It does that automatically.

**Comment by Davidyanlong** [comment]
THK, I learned
