### ISSUE TITLE
unpkg issue

### ISSUE THREAD

**Issue by matelich** [SeregPie/THREE.TextTexture#11]
https://unpkg.com/three.texttexture is no longer working correctly, not sure when it went wrong or why. Ditto for TextSprite. Might be on their end, I suppose.

Great tools, btw. I really enjoy working with them.

**Comment by SeregPie** [comment]
Thank you!

Looks like unpkg.com has problems. It's not working if you provide version:

Works: https://unpkg.com/fontfaceobserver
Doesn't: https://unpkg.com/fontfaceobserver@2.0.13

I hope it's temporary.

**Comment by matelich** [comment]
Ok, thanks (though you have Works/Doesn't backwards)

**Comment by matelich** [comment]
Oh, except https://unpkg.com/three.texttexture@18.10.24 doesn't work either. Guess I'll need to host this myself...

**Comment by SeregPie** [comment]
I hope this will be fixed soon.
https://github.com/unpkg/unpkg.com/issues/156
