### ISSUE TITLE
Sprites not showing

### ISSUE THREAD

**Issue by WonderLabWoman** [SeregPie/THREE.TextTexture#12]
Hi Sergej,
I am using TextTexture in my application (combined with A-frame). 
After your recent commits in the past couple of days, the Text-sprites are still 'there'/being created, but they are not rendered.  
I get no error in the console, and have tried different versions of A-frame, different browsers (Firefox, Chrome, Safari on Ipone), but all have the same issue.  
As soon as I reverted back to THREE.TextTexture-7a198dc077be0ed139fda80cf10eaad76eb6b1e5, all is visible again. I have not tested the inbetween commits yet.
I have not had time to investigate much into depth at this point (about to demo), but feel free to ask me to run further tests or elaborate.

**Comment by SeregPie** [comment]
hi @WonderLabWoman
i changed the way it works. maybe you were using the `imageAspect` property, which i dropped. just use `texture.image.width / texture.image.height` instead. `lineWidth` is now `strokeWidth` also. there are some breaking changes in the last version.

**Comment by WonderLabWoman** [comment]
Thank you for your quick reply!  Yes, I was using those and changing them fixed everything.  I just now saw the changes in the readme file as well.  I hope others will too ;)
I really love your work!  Thanks!
