### ISSUE TITLE
Canvas width/height not set in example

### ISSUE THREAD

**Issue by obsius** [SeregPie/THREE.TextTexture#13]
`sprite.scale.setX(texture.image.width / texture.image.height).multiplyScalar(10);`

I just upgraded from an earlier version of this library from last year, and in the above line, the image width/height isn't set until after it's called.  I think this is because the redraw fn is now async.  I switched to using `this.texture.widthInPixels` and that works.  Pretty sure it would work like in the example if redraw is called on construction instead of being pushed into the event loop, but I didn't test to see if this is the case.

**Comment by matthewgovaere** [comment]
Ran into the same issue, ended up using `widthInPixels` and `heightInPixels` like suggested above:

`mesh.scale.set(1, texture.heightInPixels / texture.widthInPixels, 1);`

...which doesn't require a delayed call.

**Comment by SeregPie** [comment]
I made an update. You will find an example in README. The redraw is throttled. Use `await texture.redraw()`.
