### ISSUE TITLE
License for TextTexture & TextSprite

### ISSUE THREAD

**Issue by PhilLehmann** [SeregPie/THREE.TextTexture#5]
HI Sergej,

Thanks you for both classes! :-)

I'd like to use them within a bachelor thesis project of mine which might one day be going commercial. Anyhow, I'd like to clarify the licenses you publish them - right now, I could not find any information about that.

E.g., three.js itself is published under MIT license: https://github.com/rohitvarkey/three-js/blob/master/threejs/LICENSE.

Thanks a lot!

**Comment by SeregPie** [comment]
Hi.
There is no license. Just use it how you like.
=)

**Comment by PhilLehmann** [comment]
Thanks for the quick reply! :)

**Comment by SeregPie** [comment]
added MIT license everywhere.
